server:
  port: 9098

logging:
  level.root: DEBUG
  level:
    com.backend.programming.learning.system.gateway.service: DEBUG

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

#gateway-service:
#  timeout-ms: 15000
#  failure-rate-threshold: 100
#  slow-call-rate-threshold: 100
#  slow-call-duration-threshold: 15000
#  permitted-num-of-calls-in-half-open-state: 200
#  sliding-window-size: 200
#  min-number-of-calls: 200
#  wait-duration-in-open-state: 3600000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 15s
      connect-timeout: 15s

security:
  paths-to-ignore: /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      cache.time-to-live: 1ms
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    urls:
      - name: core
        url: /v3/api-docs/core
      - name: auth
        url: /v3/api-docs/auth
      - name: course
        url: /v3/api-docs/course
      - name: code-assessment
        url: /v3/api-docs/code-assessment
  swagger-ui:
    urls:
      - name: core
        url: /swagger-ui/core
      - name: auth
        url: /swagger-ui/auth
      - name: course
        url: /swagger-ui/course
      - name: code-assessment
        url: /swagger-ui/code-assessment